import React, {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, Camera, CameraOff, Shield, Scale, House, Link, Unplug, Square, Play, FlaskConical, FileText, LayoutDashboard, AlertTriangle, X, RotateCcw, Pause} from 'lucide-react';
import './style.css';
import DaggerPage from './DaggerPage';
import ReplayPage from './ReplayPage';
const owner=typeof crypto.randomUUID==='function'?crypto.randomUUID():Array.from(crypto.getRandomValues(new Uint8Array(16)),v=>v.toString(16).padStart(2,'0')).join('');
const modes={disconnected:'未连接',holding:'位置保持',protect:'保护模式',gravity:'重力补偿',homing:'正在归位',testing:'无运动测试',running:'VLA 运行中'};
function Button({icon:Icon,children,...props}){return <button {...props}>{Icon&&<Icon size={18}/>}<span>{children}</span></button>}
function App(){
 const [tab,setTab]=useState(['dagger','replay'].includes(location.hash.slice(1))?location.hash.slice(1):'control');
 const [s,setS]=useState(null),[online,setOnline]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState(null),[pending,setPending]=useState(false),[form,setForm]=useState({server:'ws://127.0.0.1:8001',prompt:'pick up the plate  on the ruck.',steps:300});
 const [replayEpisode,setReplayEpisode]=useState('');
 const openReplay=episode=>{setReplayEpisode(episode);setTab('replay');location.hash='replay'};
 const token=useRef(''),initialized=useRef(false);
 async function post(path,data){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Control-Token':token.current,'X-Control-Owner':owner},body:JSON.stringify(data)});const b=await r.json();if(!r.ok)throw Error(b.error);return b;}
 useEffect(()=>{let active=true,timer;async function poll(){try{if(!token.current){token.current=(await(await fetch('/api/session')).json()).token;}await post('/api/heartbeat',{});const r=await fetch('/api/state');if(!r.ok)throw Error();const state=await r.json();if(active){setS(state);setOnline(true);if(!initialized.current){setForm(f=>({...f,server:state.server,prompt:state.prompt}));initialized.current=true;}}}catch{if(active)setOnline(false);}finally{if(active)timer=setTimeout(poll,450)}}poll();return()=>{active=false;clearTimeout(timer)}},[]);
 async function send(action,confirmed=false,extra={}){setError('');setPending(true);try{await post('/api/action',{action,...form,steps:Number(form.steps),confirmed,...extra});setConfirm(null)}catch(e){setError(e.message)}finally{setPending(false)}}
 const ask=(action,title,body,extra={})=>setConfirm({action,title,body,extra});
 const disabled=!online||pending||s?.busy||s?.latched||s?.dagger?.active;
 const ready=!disabled&&s?.connected;
 return <div className="shell"><aside><a className="brand" href="/">Kai0<span>ARX LAB CONSOLE</span></a><nav className="app-nav"><button className={tab==='control'?'selected':''} onClick={()=>{setTab('control');location.hash='control'}}><LayoutDashboard size={19}/>控制台</button><button className={tab==='dagger'?'selected':''} onClick={()=>{setTab('dagger');location.hash='dagger'}}><FlaskConical size={19}/>DAgger 采集</button><button className={tab==='replay'?'selected':''} onClick={()=>{setTab('replay');location.hash='replay'}}><RotateCcw size={19}/>Replay 回放</button></nav><div className="side-info"><span className={'dot '+(online?'live':'')}/><strong>{online?'页面服务在线':'页面服务离线'}</strong><p>ARX X5-2025 · 双臂</p><dl><dt>机械臂</dt><dd>{s?.connected?'已连接':'未连接'}</dd><dt>相机</dt><dd>{s?.cameras?'已连接':'未连接'}</dd></dl></div><footer>Kai0 / ARX<br/>VLA 测试工作台</footer></aside>
 <main><header><div><h1>{tab==='dagger'?'DAgger 采集工作台':tab==='replay'?'Replay 动作回放':'双臂控制台'}</h1><p>ARX X5-2025 <span>·</span> Kai0</p></div><div className="stop-area"><Button className="emergency" icon={Square} onClick={()=>send('stop')} disabled={!online}>软件紧急停止</Button><small><AlertTriangle size={15}/>不能替代硬件急停</small></div></header>
 {s?.demo&&<div className="banner demo">演示模式 · 不连接机械臂，不发送 CAN 命令</div>}
 {s?.exit_pending&&<div className="banner demo" role="status">后台收到退出请求，暂不释放双臂。请接管后按需归位，确认已放稳或支撑，再点“断开机械臂”完成退出。</div>}
 {online&&s?.mode==='holding'&&!s?.latched&&<div className="banner demo" role="status">JOINT 位置保持 · {s.hold_source==='sdk_home'?'保留 SDK 归位目标':'双臂及夹爪目标已固定'} · {s.hold_elapsed_s}s{s.detached?' · 后台保持，需接管后操作':' · 可继续归位或开始新任务'}。后台服务须继续运行。</div>}
 {(!online||s?.latched||error||s?.error)&&<div role="alert" className="banner danger"><AlertTriangle size={19}/><span>{!online?'页面服务连接中断，勿依赖网页停止按钮。':error||s?.error||'软件停止已锁定，请断开后重新连接。'}</span></div>}
 {tab==='replay'?<ReplayPage s={s} online={online} pending={pending} send={send} ask={ask} requestedEpisode={replayEpisode}/>:tab==='dagger'?<DaggerPage onReplay={openReplay} s={s} online={online} pending={pending} form={form} setForm={setForm} send={send} ask={ask}/>:<><div className="workspace"><div className="observation"><section><div className="section-head"><h2><Camera/>机器人观察</h2><Button disabled={disabled||s?.mode==='running'} onClick={()=>send('cameras')}>{s?.cameras?'断开相机':'连接相机'}</Button></div><div className="cameras">{[['head','顶部相机'],['left','左腕相机'],['right','右腕相机']].map(([key,label])=><div className="camera" key={key}><span className="camera-label">{label}</span>{s?.cameras&&online?<img src={'/api/camera/'+key+'?t='+Math.floor(Date.now()/600)} alt={label+'实时画面'}/>:<div className="empty-camera"><CameraOff size={32}/><p>相机未连接</p><small>等待设备画面</small></div>}</div>)}</div></section>
 <section className="telemetry"><div className="section-head"><h2><Activity/>关节状态</h2><small>{s?.state?`反馈 ${s.age_s}s 前`:'等待机械臂连接'} · rad</small></div><table><thead><tr><th>关节</th><th>左臂</th><th>右臂</th><th>参考范围</th></tr></thead><tbody>{['J1','J2','J3','J4','J5','J6','夹爪'].map((joint,i)=><tr key={joint}><td>{joint}</td><td>{s?.state?.[i]?.toFixed(5)??'—'}</td><td>{s?.state?.[i+7]?.toFixed(5)??'—'}</td><td>{s?`${s.limits.lower[i]} ~ ${s.limits.upper[i]}`:'—'}</td></tr>)}</tbody></table><div className="table-note"><Shield size={14}/>参考表仅作诊断 · 运动限位与平滑由 SDK 处理</div></section></div>
 <div className="controls"><section><div className="section-head"><h2><Shield/>设备控制</h2><span className="status"><i className={'dot '+(s?.connected?'live':'')}/>{s?.latched?'停止锁定':modes[s?.mode]||'未连接'}</span></div><div className="buttons"><Button className="blue-outline wide" icon={Pause} disabled={!online||!s?.connected||s?.latched} onClick={()=>send('pause')}>暂停并保持</Button>{s?.detached&&<Button className="wide" icon={Link} disabled={s?.busy||s?.latched} onClick={()=>ask('claim','接管后台保持','双臂正在后台保持。确认接管此页面的控制权，接管不会恢复之前的任务。')}>接管后台保持</Button>}<Button className="primary wide" icon={Link} disabled={disabled||s?.connected||s?.local_server?.status==='starting'} onClick={()=>ask('connect','连接双臂','将初始化左右臂 SDK 并请求保护模式。请确认双臂有支撑、周围无遮挡。')}>连接机械臂</Button><Button icon={Shield} disabled={!ready} onClick={()=>send('protect')}>保护模式</Button><Button icon={Scale} disabled={!ready||s?.mode!=='protect'} onClick={()=>ask('gravity','启用重力补偿','将切换双臂到重力补偿。请扶稳双臂，确认末端负载与当前标定一致。')}>重力补偿</Button><Button className="wide" icon={House} disabled={!ready||!['protect','holding'].includes(s?.mode)} onClick={()=>send('home',true)}>双臂归位</Button><Button className="outline-red wide" icon={Unplug} disabled={!online||pending||s?.busy||(!s?.connected&&!s?.latched&&!s?.cameras)} onClick={()=>ask('disconnect','断开设备','断开会释放位置保持。请先放稳或支撑双臂，再确认断开。')}>{s?.latched?'断开并解除停止锁定':'断开机械臂'}</Button></div><Button className="text-button" icon={RotateCcw} disabled={disabled||s?.connected||s?.cameras} onClick={()=>ask('release','释放采集服务','只在采集空闲、双臂处于保护模式时，停止相机采集和按钮控制服务。不会删除录制数据。')}>释放采集服务占用</Button></section>
 <section><div className="section-head"><h2><Play/>推理测试</h2><small>{s?.busy?'操作执行中':'等待操作'}</small></div><div className="server-status" role="status"><span className={'server-dot '+(s?.local_server?.status==='ready'?'green':['checking','starting','stopping'].includes(s?.local_server?.status)?'yellow':'red')}/><strong>{({ready:'就绪',checking:'检查中',starting:'加载中',stopping:'关闭中',stopped:'未启动',unavailable:'服务无响应',error:'故障'})[s?.local_server?.status]||'检查中'}</strong><span>{s?.local_server?.checkpoint_name||'place_plate / 015000'}</span></div><div className="buttons"><Button icon={Play} disabled={!online||pending||s?.busy||s?.demo||s?.connected||s?.server_stop_pending||['checking','starting','stopping','ready'].includes(s?.local_server?.status)} onClick={()=>send('server_start')}>启动 Server</Button><Button icon={Square} disabled={!online||pending||s?.demo||s?.latched||s?.detached||s?.server_stop_pending||!s?.local_server?.managed||s?.local_server?.status==='stopping'||(s?.busy&&!['running','testing'].includes(s?.mode))} onClick={()=>send('server_stop')}>关闭 Server</Button></div><p className="hint">{s?.server_stop_pending?'正在暂停任务并确认位置保持，再关闭 Server…':s?.local_server?.message}{s?.local_server?.status==='ready'&&!s?.local_server?.managed?' · 外部服务，仅监测':''}</p><label>VLA 服务地址<input readOnly value={form.server}/></label><label>任务描述（Prompt）<textarea value={form.prompt} disabled={s?.busy||s?.dagger?.active} onChange={e=>setForm({...form,prompt:e.target.value})}/></label><label>运动步数<input type="number" min="1" max="300" value={form.steps} disabled={s?.busy||s?.dagger?.active} onChange={e=>setForm({...form,steps:e.target.value})}/></label><div className="buttons"><Button className="primary" icon={FlaskConical} disabled={!ready||!s?.cameras||!['protect','holding'].includes(s?.mode)} onClick={()=>send('test')}>无运动测试</Button><Button className="blue-outline" icon={Play} disabled={!ready||!s?.cameras||!['protect','holding'].includes(s?.mode)} onClick={()=>ask('run','开始 VLA 真机运动',`将执行最多 ${form.steps} 步模型动作。软件测试通过不代表运动路径安全，请确认场景就绪并在旁准备硬件急停。`)}>开始 VLA 运动</Button></div><p className="hint">测试仅推理，不下发动作。运动结束后保持当前位置，关闭页面后转后台保持；后台服务必须保持运行。</p>{s?.result&&<div className="result" role="status">{s.result.motion?'运动执行':'无运动推理'} · {s.result.shape.join(' × ')} · {s.result.round_trip_ms} ms<br/>{s.result.violations.length?`${s.result.violations.length} 项超出参考范围，详情见日志`:'未发现参考范围越界'}</div>}</section></div></div>
 <section className="logs"><div className="section-head"><h2><FileText/>运行日志</h2><small>完整记录保存在客户端 logs 目录</small></div><div className="log-lines" aria-live="polite">{s?.events?.length?s.events.slice().reverse().map((e,i)=><div key={i} className={e.level==='error'?'log-error':''}><time>{e.time}</time><span>{e.message}{e.violations?.length>0&&<pre>{JSON.stringify(e.violations,null,2)}</pre>}</span></div>):<p>等待页面服务连接…</p>}</div></section>
 </>}
 </main>{confirm&&<div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><button className="close" aria-label="关闭" onClick={()=>setConfirm(null)}><X/></button><Shield className="modal-icon"/><h2 id="dialog-title">{confirm.title}</h2><p>{confirm.body}</p><div className="buttons"><Button onClick={()=>setConfirm(null)}>取消</Button><Button className="primary" disabled={pending} onClick={()=>send(confirm.action,true,confirm.extra)}>确认执行</Button></div></div></div>}</div>
}
createRoot(document.getElementById('root')).render(<App/>);
