import React,{useEffect,useState} from 'react';
import {Play,Pause,FolderOpen,RotateCcw,ArrowRight,Activity} from 'lucide-react';
const phases={empty:'等待选择记录',loading:'读取轨迹中',ready:'轨迹已加载',aligning:'正在前往起点',playing:'正在回放',paused:'已暂停',boundary:'片段完成 · 等待继续',complete:'回放完成',error:'加载失败'};
export default function ReplayPage({s,online,pending,send,ask,requestedEpisode}){
 const r=s?.replay||{},d=s?.dagger||{},episodes=(d.episodes||[]).filter(e=>e.status==='saved'&&!e.recoverable);
 const [episode,setEpisode]=useState(requestedEpisode||r.episode||''),[speed,setSpeed]=useState(.5);
 useEffect(()=>{if(requestedEpisode)setEpisode(requestedEpisode)},[requestedEpisode]);
 useEffect(()=>{if(!episodes.some(e=>e.episode===episode))setEpisode(episodes[0]?.episode||'')},[d.data_root,episodes.map(e=>e.episode).join('|')]);
 const part=r.parts?.[r.part],loaded=r.episode===episode&&r.total>0&&r.source_root===d.data_root;
 const locked=!online||pending||s?.busy||s?.latched||s?.detached||s?.exit_pending||s?.server_stop_pending||d.active||['running','exporting'].includes(d.task?.status);
 const canLoad=!locked&&(!s?.connected||s.mode==='holding'),canMove=canLoad&&loaded&&s?.connected&&s.mode==='holding'&&r.phase!=='complete';
 const reason=!online?'等待页面服务连接':d.active?'先结束并保存当前试验':s?.detached?'请到控制台接管后台保持':!s?.connected?'在控制台连接双臂并归位后可回放':s?.mode!=='holding'&&!s?.busy?'请先暂停并保持':!loaded?'选择记录并加载轨迹':r.phase==='complete'?'全部完成，双臂位置保持；可重新选择片段':s?.busy?'任务执行中，可随时暂停并保持':'就绪 · 回放不需要推理 Server 或相机';
 return <div className="replay-page"><div className="dagger-intro"><div><span className="eyebrow">RECORD → REVIEW → REPLAY</span><h2>让双臂重现采集轨迹</h2><p>读取已保存的关节与夹爪反馈，沿记录时间回放。原始数据保持不变。</p></div><div className="phase-pill"><span className="pulse-dot"/>{phases[r.phase]||phases.empty}</div></div>
 <div className="dagger-stats">{[['轨迹样本',r.total||0],['当前片段',r.parts?.length?`${r.part+1} / ${r.parts.length}`:'—'],['当前位置',r.total?`${Math.min(r.frame+1,r.total)} / ${r.total}`:'—'],['播放倍率',`${r.phase==='playing'?r.speed:speed} ×`]].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div>
 <div className="replay-workspace"><div><section><div className="section-head"><h2><FolderOpen size={19}/>选择采集记录</h2><small>最近保存的记录优先</small></div><label>Episode<select value={episode} disabled={locked} onChange={e=>setEpisode(e.target.value)}><option value="">请选择已保存记录</option>{episodes.map(e=><option key={e.episode} value={e.episode}>{new Date(e.created*1000).toLocaleString()} · {e.frames} 帧 · {e.prompt}</option>)}</select></label><code className="storage-current-path">{d.data_root}/episodes/{episode||'…'}</code><button className="blue-outline wide" disabled={!canLoad||!episode} onClick={()=>send('replay_load',false,{episode})}><FolderOpen size={17}/>加载轨迹（不运动）</button><p className="hint">{r.prompt||'采集结束并保存成功后，即可在此加载；无需先导出 LeRobot。'}</p></section>
 <section><div className="section-head"><h2><Activity size={19}/>轨迹片段</h2><small>蓝：策略反馈 · 橙：人工反馈</small></div><div className="replay-parts">{(r.parts||[]).map((p,i)=><button key={p.id} className={'replay-part '+(p.intervention?'human ':'')+(i===r.part?'selected':'')} disabled={!canLoad||!loaded} onClick={()=>send('replay_select',false,{part:i})}><b>{String(i+1).padStart(2,'0')} · {p.intervention?'人工纠正':'策略执行'}</b><span>{p.frames} 帧 · {p.duration_s.toFixed(1)} s</span><small>帧 {p.start_frame}–{p.end_frame}</small></button>)}</div>{!r.parts?.length&&<div className="episode-empty"><RotateCcw size={30}/><p>加载后显示可回放的连续轨迹</p></div>}<p className="hint">每个片段结束后保持，需明确继续下一段。暂停、接管等未采样区间不会自动跨越。</p></section></div>
 <div><section className="replay-transport"><div className="section-head"><h2>双臂回放控制</h2><span className={'dot '+(canMove?'live':'')}/></div><label>速度<select value={speed} disabled={locked} onChange={e=>setSpeed(Number(e.target.value))}><option value="0.25">0.25 ×</option><option value="0.5">0.5 ×（默认）</option><option value="1">1 × 采集速度</option></select></label><button className="wide" disabled={!canMove} onClick={()=>ask('replay_align','前往回放起点','双臂与夹爪将使用 SDK 默认轨迹移动到当前片段的待回放位置。请确认路径与物体状态允许该动作；到达后保持，等待开始。')}><ArrowRight size={17}/>前往起点</button><button className="primary wide" disabled={!canMove} onClick={()=>ask('replay_run','开始双臂动作回放',`按 ${speed} 倍速回放当前片段的关节与夹爪反馈。确认场景就绪；片段结束后保持，不自动进入下一段。`,{speed})}><Play size={18}/>{r.phase==='paused'?'继续当前片段':r.phase==='boundary'?'开始下一片段':'开始回放'}</button><button className="blue-outline wide" disabled={!online||!s?.connected||s?.latched} onClick={()=>send('pause')}><Pause size={18}/>暂停并保持</button><p className="hint" role="status">{reason}</p><progress max={part?part.end_frame-part.start_frame+1:1} value={part?Math.max(0,Math.min(r.frame-part.start_frame+1,part.frames)):0}/><small>{part?`当前片段：${part.intervention?'人工':'策略'} · ${part.duration_s} 秒原始轨迹`:'等待轨迹'}</small>{r.error&&<p className="dagger-error">{r.error}</p>}</section>
 <section><h2>当前反馈 / 下一目标</h2><p className="hint">弧度 · 起点一致性校验后才允许开始；限位与运动平滑沿用 SDK。</p><table className="replay-joints"><thead><tr><th>关节</th><th>左臂</th><th>右臂</th></tr></thead><tbody>{['J1','J2','J3','J4','J5','J6','夹爪'].map((name,i)=><tr key={name}><td>{name}</td>{[i,i+7].map(j=><td key={j}>{s?.state?.[j]?.toFixed(3)??'—'}<small>→ {r.target?.[j]?.toFixed(3)??'—'}</small></td>)}</tr>)}</tbody></table></section></div></div></div>
}
